name: ğŸš€ Deploy Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: â¬‡ï¸ Checkout do cÃ³digo
      uses: actions/checkout@v3

    - name: ğŸ–¥ï¸ Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: âš¡ Instalar Firebase CLI
      run: npm install -g firebase-tools

    - name: ğŸ”§ Verificar Firebase CLI
      run: firebase --version

    - name: ğŸ“‚ Listar arquivos para debug
      run: ls -R

    - name: ğŸš€ Fazer Deploy no Firebase Hosting
      run: firebase deploy --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }} --project martfleet-firebase
